### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. 

### ISSUE THREAD

**Issue by VanHelen** [NVlabs/CTG#4]
Thank you very much for your valuable research. I encountered an out of cuda memory issue while training the scenediffuser model. My device is a 4090GPU (24G), may I ask what your training configuration is like? How should I modify to train this model. Thank you very much. Looking forward to your reply.

**Comment by AIasd** [comment]
I only used 3090 and I did not encounter out of memory when using the current default config. Did you change any configs?

**Comment by VanHelen** [comment]
> 我只使用了 3090，使用当前默认配置时没有遇到内存不足的情况。您是否更改了任何配置？

Thank you very much for your reply！ I have solved this problem.
